# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog02', '0004_auto_20170509_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(null=True, verbose_name=models.CharField(max_length=200)),
        ),
    ]
